ToDoPlanning.WebUI/Models/Developer.cs
using ToDoPlanning.Entities.Concrete;

namespace ToDoPlanning.WebUI.Models
{
    public class Developer
    {
        public string Name { get; set; }
        public int Level { get; set; }
        public int DeveloperScore { get { return Level * 45; } }
        public int WorkScore { get; set; }
        public List<WorkTask> WorkTasks { get; set; } = new List<WorkTask>();
    }
}

ToDoPlanning.WebUI/Models/ErrorViewModel.cs
namespace ToDoPlanning.WebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoPlanning.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ToDoPlanning.WebUI.Models;

namespace ToDoPlanning.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ToDoPlanning.WebUI/Controllers/SprintPlanController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoPlanning.Business.Abstract;
using ToDoPlanning.WebUI.Helper;

namespace ToDoPlanning.WebUI.Controllers
{
    public class SprintPlanController : Controller
    {
        private readonly IWorkTaskBusiness _business;

        public SprintPlanController(IWorkTaskBusiness workTaskBusiness)
        {
            _business = workTaskBusiness;
        }

        public async Task<IActionResult> Index()
        {
            var taskList = await _business.GetAll();
            TempData["Week"] = taskList.GetTotalWeek();
            TempData["Hour"] = taskList.GetTotalWeek() * 45;

            return View(SprintPlan.GetSprintPlan(taskList.ToList()));
        }
    }
}

ToDoPlanning.WebUI/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoPlanning.WebUI.Helper;

namespace ToDoPlanning.WebUI.Controllers
{
    public class TaskController : Controller
    {
        public IActionResult Index()
        {
            return View(AppExtensions.CallCoreApi());
        }
    }
}

ToDoPlanning.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p><a href="http://yasinates.com.tr/" target="_blank">Learn more about Me</a> - Made With Love &hearts;</p>
</div>

ToDoPlanning.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoPlanning.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoPlanning.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoPlanning.WebUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">Set Task DataBase</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SprintPlan" asp-action="Index">Sprint Plan</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ToDoPlanning.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoPlanning.WebUI/Views/SprintPlan/Index.cshtml
@model List<Developer>

@{
    ViewData["Title"] = "Sprint Plan";
}

<div class="text-center">
    <h3>All sprint will be finished in @TempData["Week"] weeks or @TempData["Hour"] hours </h3>
    <h2 class="display-4">Developer List</h2>
    <table id="DeveloperList" class="table table-striped table-hover" style="width:100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Level</th>
                <th>One Sprint Score</th>
                <th>Total Score</th>
                <th>Total Hour</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var developer in Model)
            {
                <tr>
                    <td>@developer.Name</td>
                    <td>@developer.Level</td>
                    <td>@developer.DeveloperScore</td>
                    <td>@developer.WorkScore</td>
                    <td>@(developer.WorkScore / developer.Level)</td>
                </tr>
            }
        </tbody>
    </table>

    <h2 class="display-4">The Sprint Plan</h2>
    <table id="TaskList" class="table table-striped table-hover" style="width:100%">
        <thead>
            <tr>
                <th>Dev Name</th>
                <th>Task Name</th>
                <th>Task Sprint</th>
                <th>Task Level</th>
                <th>Task Duration</th>
                <th>Task WorkScore</th>
            </tr>
        </thead>
        <tbody>
            @for (var i = 0; i < Model.Count; i++)
            {
                @foreach (var task in Model[i].WorkTasks)
                {
                    <tr>
                        <td>@Model[i].Name</td>
                        <td>@task.Name</td>
                        <td>@task.Sprint</td>
                        <td>@task.Level</td>
                        <td>@task.Duration</td>
                        <td>@task.WorkScore</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<!--Data Table-->
<script type="text/javascript" src=" https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src=" https://cdn.datatables.net/buttons/1.2.4/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js" defer></script>

<!--Export table button CSS-->
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.4/css/buttons.dataTables.min.css">

<script>
    $(document).ready(function(){
        $('#TaskList').DataTable();
        $('#DeveloperList').DataTable();
    });
</script>

ToDoPlanning.WebUI/Views/Task/Index.cshtml
@model bool

@{
    ViewData["Title"] = "Task";
}

<div class="text-center">
    <h4 class="display-4">The result of saving the tasks to DB: @Model</h4>
</div>